name: otr_tool
description: browse otrkey files, decode and cut
publish_to: "none"
version: 1.0.1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  bot_toast: ^4.0.3
  collection: ^1.16.0
  cupertino_icons: ^1.0.4
  desktop_multi_window: ^0.1.0
  file_picker: ^4.6.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5
  flutter_markdown: ^0.6.14
  flutter_svg: ^1.1.0
  hooks_riverpod: ^2.3.2
  macos_ui: ^1.11.1
  path: ^1.8.1
  pubspec_parse: ^1.2.2
  shared_preferences: ^2.0.15

dev_dependencies:
  custom_lint: ^0.3.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  riverpod_lint: ^1.1.6
  test: ^1.16.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/files/cut_script_template.py
    - assets/images/app_icon_32x32@2x.png
    - pubspec.yaml
