name: otr_browser
description: browse otrkey files, decode and cut
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  bloc: ^8.1.1
  bot_toast: ^4.0.3
  collection: ^1.16.0
  cupertino_icons: ^1.0.4
  desktop_multi_window: ^0.1.0
  dio: ^4.0.6
  equatable: ^2.0.3
  file_picker: ^4.6.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.5
  flutter_svg: ^1.1.0
  macos_ui: ^1.11.1
  path: ^1.8.1
  provider: ^6.0.2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  test: ^1.16.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/files/cut_script_template.py
